site_name: Infodatenbanken.de
site_author: Oliver Jakoubek
site_url: https://www.infodatenbanken.de/

nav:
  - Start:
    - 'index.md'
    - 'Fragen': fragen.md
    - 'Jetzt kaufen': kaufen.md
    - Impressum: impressum.md
  - 'LÃ¤nder':
    - 'laender/index.md'
  - 'Postleitzahlen':
    - 'postleitzahlen/index.md'
  - 'Jetzt kaufen':
    - 'kaufen.md'

theme:
  name: material
  icon:
    logo: material/database-cog
  language: de
  palette:
    scheme: default
    primary: teal
    accent: teal
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
  highlightjs: true

copyright: Copyright &copy; 2022 <a href="https://www.jakoubek.net/?ref=idb">Oliver Jakoubek Software & Beratung</a>

plugins:
  - search:
      lang:
        - de
        - en
  - macros

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.caret
  - attr_list
  - md_in_html
  - admonition
  - meta

extra:
  analytics:
    provider: matomo
